version: "3.3"
services:
  instanceA:
    ports:
      - 8080:8080
    environment:
      SYNC_INSTANCES: http://instanceB:8080,http://instanceC:8080
    image: "shaad1337/myfriends:latest"

  instanceB:
    ports:
      - 8081:8080
    environment:
      SYNC_INSTANCES: http://instanceA:8080,http://instanceC:8080
    image: "shaad1337/myfriends:latest"

  instanceC:
    ports:
      - 8082:8080
    environment:
      SYNC_INSTANCES: http://instanceA:8080,http://instanceB:8080
    image: "shaad1337/myfriends:latest"
